### ISSUE TITLE
Please optimise this plugin

### ISSUE THREAD

**Issue by andris155** [SickSkillz/SLB-Tracker#12]
Please describe your request..**
A clear and concise description of what you want.
Please optimise this plugin

**Additional notes**
![jegyzet 2018-12-30 210ggg656](https://user-images.githubusercontent.com/8324198/50550857-ac210f00-0c77-11e9-9c74-62140c7555fc.jpg)
![jegyzet 2018-12-30 21fff0614](https://user-images.githubusercontent.com/8324198/50550858-ae836900-0c77-11e9-8dc8-a754f227af71.jpg)
![jegyzet 2018-12-30 210536](https://user-images.githubusercontent.com/8324198/50550859-afb49600-0c77-11e9-9c41-672881f8b682.jpg)

**Comment by SickSkillz** [comment]
~2% of a tick isn't that much. I also don't perform any heavy tasks in these events so optimization isn't really possible/needed.

**Comment by SickSkillz** [comment]
I'm going to try and work on this

**Comment by SickSkillz** [comment]
https://www.spigotmc.org/resources/superluckyblock-1-8-1-13-the-luckyblock-plugin-that-gives-you-full-control.48837/update?update=260348
