### ISSUE TITLE
Why is the custom square in the luckyblocks folder unusable, it's just a normal head, nothing?

### ISSUE THREAD

**Issue by qq59557445** [SickSkillz/SLB-Tracker#14]
Why is the custom square in the luckyblocks folder unusable, it's just a normal head, nothing?
I modified the content inside and used my own skin.

- spigot1.13.2
- java8
The server did not report any errors

**Comment by SickSkillz** [comment]
Handled over discord.
Fixed: https://www.spigotmc.org/resources/superluckyblock-1-8-1-13-the-luckyblock-plugin-that-gives-you-full-control.48837/update?update=260982
