### ISSUE TITLE
Lucky Blocks breaks PlotSquared plots

### ISSUE THREAD

**Issue by andris155** [SickSkillz/SLB-Tracker#16]
**Describe the bug**

**To Reproduce**
1. Travel to my plot
2. Place Lucky Block plot edge
3. Break Lucky Block
4. Lucky Block remove plot edge.

**Expected behavior**
Lucky Blocks breaks PlotSquared plots

**Screenshots or video**
If applicable, add screenshots or a video to help explain your problem.
![67560539_635676596939514_1898594283221417984_n](https://user-images.githubusercontent.com/8324198/62301206-6f6cfe80-b478-11e9-8420-1719c7e90d1f.jpg)

**Server (please complete the following information):**
 - Java version: AdoptOpenjdk Hotspot 11.0.4+11
 - Minecraft version: 1.14.4

**Plugin:**
 - Version: 3.1.0
 - Are you using the default config: no
 - Did you remove or add custom surprises: yes

**Debug Report:**
Please run the command /slb debug. This command will give you a link in the chat. 
Remove this line and the text under Debug Report and paste the link it gave you. 
This do nothing.

**Additional notes**

**Comment by SickSkillz** [comment]
I never got notified about this issue for some reason. Are you still experiencing this issue?
