### ISSUE TITLE
super luckyblock errors v3.4.1 - spigot 1.15.1

### ISSUE THREAD

**Issue by minecraft7net** [SickSkillz/SLB-Tracker#20]
[11:22:58] [Server thread/INFO]: [SuperLuckyBlock] Loading SuperLuckyBlock v3.4.1

on 1.15.1 spigot i have those errors
https://pastebin.com/MH0L42Aj

**Comment by SickSkillz** [comment]
I wasn't really able to reproduce this error, but I made an attempt at fixing it in the latest update: https://www.spigotmc.org/resources/superluckyblock-1-8-1-15-the-luckyblock-plugin-that-gives-you-full-control.48837/update?update=310462

If it doesn't work, please re-open this issue.
