### ISSUE TITLE
SLB >> You can't break luckyblocks in range of the road!

### ISSUE THREAD

**Issue by andris155** [SickSkillz/SLB-Tracker#9]
**Describe the bug**
SLB >> You can't break luckyblocks in range of the road! how to remove this Lucky Block?

**To Reproduce**
1. Travel to  Plotworld
2. Place Lucky Block near the road
3. Unbreakable.

**Expected behavior**

**Screenshots**
![2018-12-13_08 04 43](https://user-images.githubusercontent.com/8324198/49921550-34e53000-feae-11e8-90b7-8f8f25e2251f.png)

**Server (please complete the following information):**
 - OS: Ubuntu 16.04
 - Java version: 11
 - Minecraft version: 1.13.2

**Plugin (please complete the following information):**
 - Version: 2.13.1
 - Changed config: yes
 - Added or removed custom surprises: yes

**Additional notes**

**Comment by SickSkillz** [comment]
Oops, that's not how that should work. I will fix it asap. Thanks for reporting!

**Comment by SickSkillz** [comment]
This has been fixed in the latest update(2.13.2).
